on:
  push:
    tags:
      - v*
  workflow_dispatch:

name: create-release

jobs:
  build:
    name: Create release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - uses: dtolnay/rust-toolchain@stable

      - uses: extractions/setup-just@v1

      - name: Build project
        run: just build

      - name: Create workflow
        run: |
          cp target/release/masked-email workflow
          cd workflow && zip -rq ../masked-email.alfredworkflow .

      - name: Create release
        run: |
          UPLOAD_URL="$(
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/releases \
              -d '{"tag_name":"${{ github.action_ref }}","target_commitish":"${{ github.action_ref }}","name":"${{ github.action_ref }}","body":"# ${{ github.action_ref }}","draft":true,"prerelease":false,"generate_release_notes":false}' \
            | jq --raw-output .upload_url)"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/zip" \
            "${UPLOAD_URL/'{?name,label}'/?name=pirate-weather.alfredworkflow}" \
            --data-binary "@pirate-weather.alfredworkflow"
